USE [ERPMediatorDB]
GO
/****** Object:  View [dbo].[EmplMgrHierarchy]    Script Date: 1/26/2018 2:43:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[EmplMgrHierarchy] AS
SELECT		
			
			WORKER.PERSONNELNUMBER AS 'EmplID', PERSON.NAME AS 'EmplNameEN', PERSON.ARABICNAME AS 'EmplNameAR',
			PERSON.NATIONALITY AS 'EmplNationality', PERSON.QUALIFICATION AS 'EmplQualification',
			PERSON.RELIGION AS 'EmplReligion', PERSON.DAPHIRINGTYPE AS 'EmplHiringType',
			POSITION.POSITIONID AS 'EmplPositionID', PDETAIL.DESCRIPTION AS 'EmplPositionName',
			PORGIZATION.OMOPERATINGUNITNUMBER AS 'EmplPositionDeptNo', PORGIZATION.NAME AS 'EmplPositionDeptName',
			PTITLE.TITLEID AS 'EmplPositionTitle', ETITLE.TITLEID AS 'EmplTitle',
			MANAGER.PERSONNELNUMBER AS 'MgrEmplID', MGRNAME.NAME AS 'MgrEmplNameEN',
			MGRNAME.ARABICNAME AS 'MgrEmplNameAR',
			PPOSITION.POSITIONID AS 'MgrPositionID', PPDETAIL.DESCRIPTION AS 'MgrPositionName',
			PPORGIZATION.OMOPERATINGUNITNUMBER AS 'MgrPositionDeptNo', PPORGIZATION.NAME as 'MgrPositionDeptName'
			


FROM [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMWORKER AS WORKER

INNER JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMEMPLOYMENT AS EMPLOYEE
ON EMPLOYEE.WORKER = WORKER.RECID
AND EMPLOYEE.VALIDTO >= CAST(GETDATE() as date)

INNER JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.DIRPARTYTABLE AS PERSON
ON PERSON.RECID = WORKER.PERSON


LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONWORKERASSIGNMENT AS PWORKER
ON PWORKER.WORKER = WORKER.RECID
AND PWORKER.VALIDTO >= CAST(GETDATE() as date)


LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITION AS POSITION
ON PWORKER.POSITION = POSITION.RECID


LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONDETAIL AS PDETAIL
ON PWORKER.POSITION = PDETAIL.POSITION
AND PDETAIL.POSITION = POSITION.RECID
AND PDETAIL.VALIDTO >= CAST(GETDATE() as date)

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.DIRPARTYTABLE AS PORGIZATION
ON PDETAIL.DEPARTMENT = PORGIZATION.RECID

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMTITLE	PTITLE
ON PDETAIL.TITLE = PTITLE.RECID

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMWORKERTITLE AS WTITLE
ON WTITLE.WORKER = WORKER.RECID
AND WTITLE.VALIDTO >= CAST(GETDATE() as date)

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMTITLE	ETITLE
ON WTITLE.TITLE = ETITLE.RECID

INNER JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONHIERARCHY AS PHIERARCHY
ON PHIERARCHY.POSITION = POSITION.RECID
AND PHIERARCHY.VALIDTO >= CAST(GETDATE() as date)

INNER JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONDETAIL AS PPDETAIL
ON PPDETAIL.POSITION = PHIERARCHY.PARENTPOSITION
AND PPDETAIL.VALIDTO >= CAST(GETDATE() as date)

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.DIRPARTYTABLE AS PPORGIZATION
ON PPORGIZATION.RECID = PPDETAIL.DEPARTMENT

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITION AS PPOSITION
ON PPOSITION.RECID = PHIERARCHY.PARENTPOSITION

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONWORKERASSIGNMENT AS PMANAGER
ON PMANAGER.POSITION = PHIERARCHY.PARENTPOSITION
AND PMANAGER.VALIDTO >= CAST(GETDATE() as date)

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMWORKER AS MANAGER
ON MANAGER.RECID = PMANAGER.WORKER

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.DIRPARTYTABLE AS MGRNAME
ON MGRNAME.RECID = MANAGER.PERSON

GO
/****** Object:  View [dbo].[EmpVacInfo]    Script Date: 1/26/2018 2:43:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[EmpVacInfo] AS


SELECT		EmpVacInfo.WORKERPN AS 'EmpNo', EmpVacInfo.LEAVEREQUESTID AS 'VacID',
			EmpVacInfo.FROMDATE AS 'VacStartDate', EmpVacInfo.TODATE AS 'VacEndDate',
			EmpVacInfo.LEAVEDAYS AS 'VacDaysNo', EmpVacInfo.LEAVEID AS 'VacationTypeNo',
			VacationType.DESCRIPTION AS 'VacationTypeName'

FROM		[HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].[dbo].[DAPLEAVEREQUEST] AS EmpVacInfo

INNER JOIN	[HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].[dbo].[DAPLEAVES] AS VacationType
ON			EmpVacInfo.LEAVEID = VacationType.LEAVEID

WHERE	EmpVacInfo.WORKFLOWSTATE = 4
GO
/****** Object:  View [dbo].[UserEmplMgrHierarchy]    Script Date: 1/26/2018 2:43:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[UserEmplMgrHierarchy] AS
   

SELECT		
			
			UI.NETWORKALIAS AS 'UserID', CONCAT(SUBSTRING(UI.NETWORKDOMAIN,1,7),'\',UI.NETWORKALIAS) AS 'UserIDwithDomain',
			SUI.EMAIL AS 'UserEmailAddress', WORKER.PERSONNELNUMBER AS 'EmplID', 
			PERSON.NAME AS 'EmplNameEN', PERSON.ARABICNAME AS 'EmplNameAR',
			PERSON.NATIONALITY AS 'EmplNationality', PERSON.QUALIFICATION AS 'EmplQualification', PERSON.RELIGION AS 'EmplReligion',
			PERSON.DAPHIRINGTYPE AS 'EmplHiringType', POSITION.POSITIONID AS 'EmplPositionID',
			PDETAIL.DESCRIPTION AS 'EmplPositionName', PORGIZATION.NAME AS 'EmplPositionDept',
			PTITLE.TITLEID AS 'EmplPositionTitle', ETITLE.TITLEID AS 'EmplTitle',
			PPOSITION.POSITIONID AS 'MgrPositionID', PPDETAIL.DESCRIPTION AS 'MgrPositionName',
			MANAGER.PERSONNELNUMBER AS 'MgrEmplID', MGRNAME.NAME AS 'MgrEmplNameEN',
			MGRNAME.ARABICNAME AS 'MgrEmplName', MUI.NETWORKALIAS AS 'MgrUserID',
			CONCAT(SUBSTRING(MUI.NETWORKDOMAIN,1,7),'\',MUI.NETWORKALIAS) AS 'MgrUserIDwithDomain',
			MSUI.EMAIL AS 'MgrEmailID'


FROM [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.USERINFO AS UI

INNER JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.SYSUSERINFO AS SUI
ON SUI.ID = UI.ID

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.DIRPERSONUSER AS UR
ON UR.USER_ = UI.ID
AND UR.VALIDTO >= CAST(GETDATE() as date)


LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.DIRPARTYTABLE AS PERSON
ON UR.PERSONPARTY = PERSON.RECID

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMWORKER AS WORKER
ON WORKER.PERSON = PERSON.RECID

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMEMPLOYMENT AS EMPLOYEE
ON EMPLOYEE.WORKER = WORKER.RECID
AND EMPLOYEE.VALIDTO >= CAST(GETDATE() as date)

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONWORKERASSIGNMENT AS PWORKER
ON PWORKER.WORKER = WORKER.RECID
AND PWORKER.VALIDTO >= CAST(GETDATE() as date)


LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITION AS POSITION
ON PWORKER.POSITION = POSITION.RECID


LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONDETAIL AS PDETAIL
ON PWORKER.POSITION = PDETAIL.POSITION
AND PDETAIL.POSITION = POSITION.RECID
AND PDETAIL.VALIDTO >= CAST(GETDATE() as date)

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.DIRPARTYTABLE AS PORGIZATION
ON PDETAIL.DEPARTMENT = PORGIZATION.RECID

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMTITLE	PTITLE
ON PDETAIL.TITLE = PTITLE.RECID

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMWORKERTITLE AS WTITLE
ON WTITLE.WORKER = WORKER.RECID
AND WTITLE.VALIDTO >= CAST(GETDATE() as date)

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMTITLE	ETITLE
ON WTITLE.TITLE = ETITLE.RECID

INNER JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONHIERARCHY AS PHIERARCHY
ON PHIERARCHY.POSITION = POSITION.RECID
AND PHIERARCHY.VALIDTO >= CAST(GETDATE() as date)

INNER JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONDETAIL AS PPDETAIL
ON PPDETAIL.POSITION = PHIERARCHY.PARENTPOSITION
AND PPDETAIL.VALIDTO >= CAST(GETDATE() as date)

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITION AS PPOSITION
ON PPOSITION.RECID = PHIERARCHY.PARENTPOSITION

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMPOSITIONWORKERASSIGNMENT AS PMANAGER
ON PMANAGER.POSITION = PHIERARCHY.PARENTPOSITION
AND PMANAGER.VALIDTO >= CAST(GETDATE() as date)

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.HCMWORKER AS MANAGER
ON MANAGER.RECID = PMANAGER.WORKER

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.DIRPARTYTABLE AS MGRNAME
ON MGRNAME.RECID = MANAGER.PERSON

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.DIRPERSONUSER MUR
ON MUR.PERSONPARTY = MGRNAME.RECID
AND MUR.PERSONPARTY = MANAGER.PERSON
AND MUR.VALIDTO >= CAST(GETDATE() as date)


LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.SYSUSERINFO MSUI
ON MSUI.ID = MUR.USER_

LEFT JOIN [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].DBO.USERINFO MUI
ON MUI.ID = MUR.USER_
AND MUI.ID = MSUI.ID

GO
/****** Object:  View [dbo].[VacationType]    Script Date: 1/26/2018 2:43:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create view [dbo].[VacationType] AS
select LEAVEID as 'VacationTypeNo', DESCRIPTION as 'VacationTypeName'
from [HQDB-PR-CLS05\SQLLIVE2].[MicrosoftDynamicsAX].[dbo].DAPLEAVES as VacationType
GO
